### ISSUE TITLE
arxiv paper

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-349#1]
please use proper urls in the refernce section
 The sentence "Previous racing prediction attempts such as [^2][^5][^6][^7] could not make real-time predictions because the data they used was based on Lap, that is, new data would only be generated when the car passed a specific position. And we will try to use high-frequency telemetry data to make predictions." is insufficient. Relationship to arxiv paper must be in detail explained

**Comment by laszewsk** [comment]
please use proper urls in the refernce section
 The sentence "Previous racing prediction attempts such as [^2][^5][^6][^7] could not make real-time predictions because the data they used was based on Lap, that is, new data would only be generated when the car passed a specific position. And we will try to use high-frequency telemetry data to make predictions." is insufficient. Relationship to arxiv paper must be in detail explained

**Comment by LL145** [comment]
Thanks for your advice.

This article is different from [^7] in at least three points:

The resolution of the data is different. This article uses telemetry data. The telemetry data generates 7 to 8 data points per second. After preprocessing, we sample the data to 1 data point per second. The data used in [^7] is based on "Lap", that is, the new data will only be recorded when the car passes the starting point.

The prediction model is different. This article uses LSTM for prediction, while [^7] uses DeepAR-based models for prediction.

The definition of ranking is different. What this article predicts is: Given a certain time t, predict which car will lead at t+tp. And the output of [^7] is: predict the rank of each car to complete the nth lap. One is to predict the position of the car in space at a given time; the other is to give a spatial position (usually the starting point of the track), and then predict the time for the car to pass that position.

I added this comparison to the report.

**Comment by laszewsk** [comment]
great. I ha e no time to reread, but I hope you understand what needs to be done.

close this when done. It would still be problematic if you do not explicitly describe the difference. If you have done it sufficiently that is ok. This is also a lesson for the future. If you were to have major work done elsewhere even in another class you MUST mention it and delineate via explicit explanations what is different. This is what is needed by the scientific community. 
So close this when done.
